### PR TITLE
Support for OSBA and p-MySQL

### PR DESCRIPTION
**Pull request by HDYA**

### CODE REVIEW

**Comment by HDYA** [comment]
Hi @bingosummer , Can you help review it?

**Comment by bingosummer** [comment]
LGTM.
CC @zhongyi-zhang and @norshtein, who are actively working on OSBA.

**Comment by HDYA** [comment]
Hi @davewalter ,
Could you help merge this PR?
Thanks

**Comment by davewalter** [comment]
Hi @HDYA,

> Could you help merge this PR?
> Thanks

Sorry for the delay (vacation). I'm afraid that I am no longer on the Diego Persistence team. @paulcwarren or @DennisDenuto should be able to help with this.

Regards,
Dave

**Comment by HDYA** [comment]
Thanks @davewalter

**Comment by paulcwarren** [comment]
cc /@cloudfoundry/cf-diego-persistence

**Pull request merged**
